# Generated by Django 5.1 on 2024-11-19 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0003_remove_faculty_coordinator'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='faculty',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='faculties.faculty'),
        ),
    ]
