# Generated by Django 5.1 on 2024-12-04 01:46

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_coordinator_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to=user.models.upload_profile_picture),
        ),
        migrations.AddField(
            model_name='speaker',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to=user.models.upload_profile_picture),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to=user.models.upload_profile_picture),
        ),
    ]
