# Generated by Django 5.1 on 2024-10-16 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_events', to='faculties.faculty'),
        ),
    ]
