# Generated by Django 5.1 on 2024-09-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
