# Generated by Django 5.1 on 2024-10-16 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_student_organizer'),
        ('faculties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_event_types', to='faculties.faculty'),
            preserve_default=False,
        ),
    ]
