# Generated by Django 5.1 on 2024-11-19 20:39

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventtype_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='promotional_image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.upload_promotional_image),
        ),
    ]
