# Generated by Django 5.1 on 2024-11-19 20:53

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_promotional_image'),
        ('user', '0002_coordinator_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='user.speaker'),
        ),
        migrations.AlterField(
            model_name='event',
            name='promotional_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=events.models.upload_promotional_image),
        ),
        migrations.AlterField(
            model_name='event',
            name='student_organizer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_organizer', to='user.student'),
        ),
    ]
