# Generated by Django 5.1 on 2024-11-20 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_speaker_alter_event_promotional_image_and_more'),
        ('user', '0002_coordinator_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='speaker',
        ),
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_speakers', to='events.event')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_speaked', to='user.speaker')),
            ],
            options={
                'db_table': 'event_speakers',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(related_name='speaked_events', through='events.EventSpeaker', to='user.speaker'),
        ),
    ]
