# Generated by Django 5.1 on 2024-12-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_speaker_eventspeaker_event_speakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
