# Generated by Django 5.1 on 2024-12-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
