# Generated by Django 5.1 on 2024-12-03 21:13

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='promotional_image',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to=events.models.upload_promotional_image),
        ),
    ]
