# Generated by Django 5.1 on 2024-09-20 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='students',
            field=models.ManyToManyField(related_name='faculties', to=settings.AUTH_USER_MODEL),
        ),
    ]
