# Generated by Django 5.1 on 2024-11-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='coordinator',
        ),
    ]
